# Combine features with functions

Creating new features from existing ones using mathematical operations. A practical and common example is calculating the Body Mass Index (BMI) using weight and height.

In [18]:
import pandas as pd

In [19]:
# create a dataframe with student data
df = pd.DataFrame({
    'student_id': [1, 2, 3, 4, 5],
    'height_cm': [170, 160, 175, 180, 165],
    'weight_kg': [70, 55, 80, 90, 60]
})

display(df)

   student_id  height_cm  weight_kg
0           1        170         70
1           2        160         55
2           3        175         80
3           4        180         90
4           5        165         60

## Calculate BMI

The formula for BMI is:

$$ BMI = \frac{weight (kg)}{(height (m))^2} $$

We can perform this calculation directly using vectorized operations on the dataframe columns.

In [20]:
# calculate BMI using vectorized operations
# Note: we divide height by 100 to convert cm to meters
df['bmi'] = df['weight_kg'] / (df['height_cm'] / 100) ** 2

display(df)

   student_id  height_cm  weight_kg        bmi
0           1        170         70  24.221453
1           2        160         55  21.484375
2           3        175         80  26.122449
3           4        180         90  27.777778
4           5        165         60  22.038567

## Create Categories with Custom Functions

Sometimes we want to apply more complex logic to create features. We can use python functions for this. For example, let's categorize the BMI values.

In [21]:
def get_bmi_category(bmi):
    if bmi < 18.5:
        return 'Underweight'
    elif 18.5 <= bmi < 25:
        return 'Normal'
    elif 25 <= bmi < 30:
        return 'Overweight'
    else:
        return 'Obese'

# apply the function to the bmi column
df['bmi_category'] = df['bmi'].apply(get_bmi_category)

display(df)

   student_id  height_cm  weight_kg        bmi bmi_category
0           1        170         70  24.221453       Normal
1           2        160         55  21.484375       Normal
2           3        175         80  26.122449   Overweight
3           4        180         90  27.777778   Overweight
4           5        165         60  22.038567       Normal